### ISSUE TITLE
The savegame not loading

### ISSUE THREAD

**Issue by Jerome2103** [Valerate/CORE-DyTech-Core#4]
This Error comming, when i load my savegame
![image](https://cloud.githubusercontent.com/assets/27641713/25086710/e6d4917e-2369-11e7-9473-02922d8900a9.png)

**Comment by Valerate** [comment]
What other mods do you have installed?

**Comment by Valerate** [comment]
Go into dytech-core and just delete the "migration" folder

**Comment by Jerome2103** [comment]
treefarm.
i'm testing now

Thx. is fixed
